#!/bin/bash

NAME=${PWD##*docker-}
IMAGE_NAME=${USER%%-*}/${NAME}
docker rm ${NAME}

set -x
if [ "${1}" = "bash" ]; then
    docker run -v ${PWD}:/work -i -t --name=${NAME} ${IMAGE_NAME} /bin/bash
else
    docker run -d -v ${PWD}:/work --name=${NAME} ${IMAGE_NAME} 
fi
